name: weather
description: A simple weather app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  intl:
  
  #animation
  lottie: ^2.7.0
  shimmer: ^3.0.0

  #logging
  logger: ^2.0.2+1

  #state mgmt
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #functional prog
  fpdart: ^1.1.0

  #routing
  auto_route: ^7.8.4
  
  #injection and code gen
  freezed_annotation:
  injectable: ^2.3.2
  get_it: ^7.6.4

  #api calls
  dio: ^5.3.3

  #location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #injection and code gen
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: WeatherIcons
      fonts:
        - asset: lib/core/icons/WeatherIcons.ttf


  assets:
    - assets/weather_animations/

 